name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  id-token: write
  contents: read

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test --trace on
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Upload HTML report to Azure
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          REPORT_DIR='run-${{ github.run_id }}-${{ github.run_attempt }}'
          azcopy cp --recursive "./playwright-report/*" "https://${{ vars.STORAGE_ACCOUNT_NAME }}.blob.core.windows.net/\$web/$REPORT_DIR"
          echo "::notice title=HTML report url::https://${{ vars.STORAGE_ACCOUNT_NAME }}.z13.web.core.windows.net/$REPORT_DIR/index.html"
